#!/bin/bash
echo "pls enter filename."
read fname
echo "enter the age of employee."
read n
echo"==============================="
echo "list of employees whose age is $n"
echo "==============================="
sed '1d' $fname>temp
while read line
do
age=`echo "$line"|awk -F " " '{print $3}'`
if [$age -ge $n]
then
echo "$line"|awk -F " " '{print $1}'
else
echo "no employees found in the given age $n"
------------
